version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ivis-core
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: ivis-core
      MARIADB_ROOT_PASSWORD: alpha

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  es:
    image: elasticsearch:6.8.23
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es:9200
    depends_on:
      - es
    ports:
      - 5601:5601

  ivis:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile-dev-final
    volumes:
      # fine-grained volume mapping so as to not collide with built packages from the dockerfile build
      - ./config/ivis:/opt/ivis-core/server/config:ro
      - ./ivis-core/server/src:/opt/ivis-core/server/src
      - ./ivis-core/server/routes:/opt/ivis-core/server/routes
      - ./ivis-core/server/models:/opt/ivis-core/server/models
      - ./ivis-core/server/services:/opt/ivis-core/server/services
      - ./ivis-core/server/lib:/opt/ivis-core/server/lib
      - ./ivis-core/server/index.js:/opt/ivis-core/server/index.js
      - ./ivis-core/client/src:/opt/ivis-core/client/src
    depends_on:
      - db
      - es
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"