version: '3.1'

services:

  tapache:
    container_name: proxy
    image: httpd:2.4.54
    volumes:
      - ./config/apache/apache.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/apache/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
      # assumes the certificates are generated locally first and copied into this location
      # TODO
      # should be changed to NEVER be required to be copied
      - ./config/ivis-cert/server.cert:/opt/server.cert.pem:ro
      - ./config/ivis-cert/server.pem:/opt/server.key.insecure:ro
      - ./config/ivis-cert/ca.cert:/opt/ca.cert.pem:ro
    ports:
       - "443:443"
       - "8446:8446"
       - "80:80"
    networks:
      ivis-net:
        aliases: 
         - ivis.tapache
         - api.tapache
         - sbox.tapache
    

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_USER: ivis-core
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: ivis-core
      MYSQL_ROOT_PASSWORD: alpha
    volumes:
      - ./data:/var/lib/mysql
    networks:
      ivis-net:


  es:
    container_name: es
    image: elasticsearch:6.8.23
    networks:
      ivis-net:

  ivis:
    container_name: IVIS-Core
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile-dev-final
    volumes:
      # ivis configuration
      - ./config/ivis:/opt/ivis-core/server/config:ro
      # TODO adjust paths
      # certificates (only for sending as client certificates and accepting locally-issued certificates)
      - ./config/ivis-cert/server.cert:/opt/server.cert.pem:ro
      - ./config/ivis-cert/server.pem:/opt/server.key.insecure:ro
      - ./config/ivis-cert/ca.cert:/opt/ca.cert.pem:ro
      # assumes the certificates are generated locally first
      - ./ivis-core/server/certs/remote:/opt/ivis-core/server/certs/remote

      # development files
      # fine-grained volume mapping so as to not collide with built packages from the dockerfile build
      - ./ivis-core/server/src:/opt/ivis-core/server/src
      - ./ivis-core/server/routes:/opt/ivis-core/server/routes
      - ./ivis-core/server/models:/opt/ivis-core/server/models
      - ./ivis-core/server/services:/opt/ivis-core/server/services
      - ./ivis-core/server/lib:/opt/ivis-core/server/lib
      - ./ivis-core/server/index.js:/opt/ivis-core/server/index.js
      - ./ivis-core/server/app-builder.js:/opt/ivis-core/server/app-builder.js
      - ./ivis-core/client/src:/opt/ivis-core/client/src
      - ./ivis-core/files:/opt/ivis-core/server/files

    depends_on:
      - db
      - es
      - tapache
    networks:
      ivis-net:

# development interfaces
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      ivis-net:

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es:9200
    depends_on:
      - es
    ports:
      - 5601:5601
    networks:
      ivis-net:
networks:
  ivis-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.80.0.0/16