version: '3.1'

services:

  tapache:
    container_name: proxy
    image: httpd:2.4.54
    volumes:
      - ./config/apache/apache.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/apache/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
      # assumes the certificates are generated locally first
      # here goes either the IVIS server certificate, or your official fullchain file
      - /etc/letsencrypt/live/domain/fullchain.pem:/opt/server.pem:ro
      # here goes the key for the above certificate
      - /etc/letsencrypt/live/domain/privkey.pem:/opt/server.key:ro
      # here goes the local CA certificate as generated in ivis-core/certs/remote/ca folder
      - ./ivis-core/server/certs/remote/ca/ca.cert:/opt/ca.cert:ro
    ports:
    # exposes ivis, sbox and api endpoints
       - "443:443"
    # exposes SSL-secured elasticsearch
    # client connections to this port require a certificate from the local CA 
       - "8446:8446"
    # exposes HTTP->HTTPS redirect
       - "80:80"
    

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_USER: ivis-core
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: ivis-core
      MYSQL_ROOT_PASSWORD: alpha
    volumes:
      - ./data:/var/lib/mysql


  es:
    container_name: es
    image: elasticsearch:6.8.23

  ivis:
    container_name: IVIS-Core
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      # ivis configuration, go ahead and edit the file, this entry does not need to be edited
      - ./config/ivis:/opt/ivis-core/server/config:ro
      # assumes the certificates are generated locally first
      # certificate names can be configured in the ivis config
      - ./ivis-core/server/certs/remote:/opt/ivis-core/server/certs/remote

      # copy the OCI config file here, use the /opt/oci_key as the key_file 
      - ./config/config.txt:/opt/oci_config
      # insert the location to the OCI-associated private key
      - ./config/key.txt:/opt/oci_key

      # bind valid SSH key pair (use remote-exec-ssh-init.sh to skip setting this up on your own)
      # WARNING!!! use `ssh-keygen -t ecdsa`, DO NOT USE THE DEFAULT TYPE
      #   - due to ssh2 package compatibility...
      # used for remote executor communication
      - ./config/ecd.pub:/opt/ssh_pub
      - ./config/ecd:/opt/ssh_prv
      
      # persistence
      - ./ivis-core/files:/opt/ivis-core/server/files

    depends_on:
      - db
      - es
      - tapache