FROM centos:7
WORKDIR /opt
RUN yum update -y
RUN yum install -y epel-release
RUN curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install -y install \
    nodejs \
    #redis \
    pwgen \
    gcc-c++ make bzip2  \
    java-1.8.0-openjdk \
    git \
    libXScrnSaver \
    at-spi2-atk \
    gtk3 
RUN yum install -y git python3 python3-pip
ARG CACHEBUST=1
RUN echo "cache-bust" && git clone https://github.com/BohdanQQ/ivis-core.git
WORKDIR /opt/ivis-core
RUN git pull
RUN git checkout remote-jobs
RUN python3 -m pip install --user --upgrade setuptools wheel
COPY ./docker-install-centos.sh ./docker-install-centos.sh
COPY ./functions-centos ./functions-centos
RUN /bin/bash ./docker-install-centos.sh
RUN npm install -g nodemon
EXPOSE 8080 8081 8082
COPY ./docker-entry.sh ./docker-entry.sh
ENTRYPOINT [ "bash", "/opt/ivis-core/docker-entry.sh" ]