version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ivis-core
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: ivis-core
      MARIADB_ROOT_PASSWORD: alpha

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  es:
    image: elasticsearch:6.8.23
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es:9200
    depends_on:
      - es
    ports:
      - 5601:5601

  ivis:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile-centos
    depends_on:
      - db
      - es
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"